# Generated by Django 2.2.4 on 2019-08-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('RegDate', models.DateTimeField(verbose_name='date registrated')),
                ('Address', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=30)),
            ],
        ),
    ]
